export const Users =[
    {"id":1,
    "startplace":"TRV",
    "destination":"dub",
    "checkintime":"1.pm",
    "checkouttime":"4pm",
    "adult":2,
    "children":0,
    "date":"jun 10",
    "amount":"INR 14000",
    "flightname":"AirIndia"
},
{"id":2,
"startplace":"cok",
"destination":"TRV",
"checkintime":"2.am",
"checkouttime":"3.pm",
"adult":2,
"children":0,
"date":"jun 10",
"amount":"INR 24000",
"flightname":"AirIndia"
},
{"id":3,
"destination":"RUH",
"startplace":"cok",

"checkintime":"5.pm",
"checkouttime":"8pm",
"adult":1,
"children":0,
"date":"jun 10",
"amount":"INR 35000",
"flightname":"indigo"
},
{"id":4,
"destination":"RUH",
"startplace":"cok",
"checkintime":"5.pm",
"checkouttime":"6pm",
"adult":1,
"children":0,
"date":"jun 10",
"amount":"INR 45000",
"flightname":"indigo"
},
{"id":5,
"destination":"RUH",
"startplace":"cok",
"checkintime":"9.pm",
"checkouttime":"10pm",
"adult":1,
"children":0,
"date":"jun 10",
"amount":"INR 65000",
"flightname":"indigo"
},
]